### ISSUE TITLE
error[E0308]: mismatched types

### ISSUE THREAD

**Issue by felix143** [eikendev/urlprobe#3]
I received an error while installation, kindly help me to resolve this
![image](https://github.com/eikendev/urlprobe/assets/34566338/6d650846-d604-4b46-ba26-67f91f2c23b2)
![image](https://github.com/eikendev/urlprobe/assets/34566338/a33dba1e-9d0e-4a07-a6c4-a90b9f73fe4d)

**Comment by eikendev** [comment]
Thanks for reporting this issue, which should be closed in fd13e77003ffd59b9fc2c5d47c85c48b231cffa8. Kindly let me know if version 0.4.0 works for you.

**Comment by felix143** [comment]
> Thanks for reporting this issue, which should be closed in [fd13e77](https://github.com/eikendev/urlprobe/commit/fd13e77003ffd59b9fc2c5d47c85c48b231cffa8). Kindly let me know if version 0.4.0 works for you.

Yes it worked
